/**
 * spa5k/tafsir_api edition catalog — ALL languages (115 editions, 33 languages).
 *
 * Generated from https://cdn.jsdelivr.net/gh/spa5k/tafsir_api@main/tafsir/editions.json
 * (duplicated language+name pairs collapsed to their first slug).
 *
 * Verse content lives at:
 *   https://cdn.jsdelivr.net/gh/spa5k/tafsir_api@main/tafsir/{slug}/{surah}/{ayah}.json
 */

export interface Spa5kEdition {
  slug:       string;
  name:       string;
  authorName: string;
  /** ISO 639-1 code, e.g. "en", "ar", "ur" */
  language:   string;
}

/** Display names for every language code in the catalog. */
export const TAFSIR_LANGUAGE_NAMES: Record<string, string> = {
  "ar": "Arabic",
  "as": "Assamese",
  "az": "Azerbaijani",
  "bn": "Bengali",
  "bs": "Bosnian",
  "en": "English",
  "es": "Spanish",
  "fa": "Persian",
  "ff": "Fulah",
  "fr": "French",
  "hi": "Hindi",
  "id": "Indonesian",
  "it": "Italian",
  "ja": "Japanese",
  "km": "Khmer",
  "ku": "Kurdish",
  "ky": "Kyrgyz",
  "ml": "Malayalam",
  "ps": "Pashto",
  "ru": "Russian",
  "si": "Sinhala",
  "sq": "Albanian",
  "sr": "Serbian",
  "ta": "Tamil",
  "te": "Telugu",
  "th": "Thai",
  "tl": "Tagalog",
  "tr": "Turkish",
  "ug": "Uyghur",
  "ur": "Urdu",
  "uz": "Uzbek",
  "vi": "Vietnamese",
  "zh": "Chinese",
};

export const SPA5K_EDITIONS: Spa5kEdition[] = [
  { slug: "abu-bakr-jabir-al-jazairi", name: "Abu Bakr Jabir Al-Jazairi", authorName: "Abu Bakr Jabir Al-Jazairi", language: "ar" },
  { slug: "adwa-al-bayan", name: "Adwa' Al-Bayan", authorName: "Adwa' Al-Bayan", language: "ar" },
  { slug: "al-dur-al-masun-lil-samin-al-halabi", name: "Al Dur Al Masun Lil Samin Al Halabi", authorName: "Al Dur Al Masun Lil Samin Al Halabi", language: "ar" },
  { slug: "al-jadwal-fi-i-rab-al-quran", name: "Al Jadwal fi I'rab Al Quran", authorName: "Al Jadwal fi I'rab Al Quran", language: "ar" },
  { slug: "al-lubab-fi-ulum-al-kitab", name: "Al Lubab fi Ulum Al Kitab", authorName: "Al Lubab fi Ulum Al Kitab", language: "ar" },
  { slug: "al-nashr-li-ibn-al-jazari", name: "Al Nashr li Ibn Al Jazari", authorName: "Al Nashr li Ibn Al Jazari", language: "ar" },
  { slug: "al-qira-at-al-mawsoo-ah-al-qur-aniyyah", name: "Al Qira'at Al Mawsoo'ah Al Qur'aniyyah", authorName: "Al Qira'at Al Mawsoo'ah Al Qur'aniyyah", language: "ar" },
  { slug: "al-bahr-al-muhit", name: "Al-Bahr Al-Muhit", authorName: "Al-Bahr Al-Muhit", language: "ar" },
  { slug: "al-basit", name: "Al-Basit", authorName: "Al-Basit", language: "ar" },
  { slug: "al-durr-al-manthur", name: "Al-Durr Al-Manthur", authorName: "Al-Durr Al-Manthur", language: "ar" },
  { slug: "al-kashshaf-al-zamakhshari", name: "Al-Kashshaf Al-Zamakhshari", authorName: "Al-Kashshaf Al-Zamakhshari", language: "ar" },
  { slug: "al-muharrar-al-wajiz-ibn-atiyyah", name: "Al-Muharrar Al-Wajiz Ibn Atiyyah", authorName: "Al-Muharrar Al-Wajiz Ibn Atiyyah", language: "ar" },
  { slug: "al-muyassar-fi-al-gharib", name: "Al-Muyassar fi Al-Gharib", authorName: "Al-Muyassar fi Al-Gharib", language: "ar" },
  { slug: "al-wajiz-wahidi", name: "Al-Wajiz Wahidi", authorName: "Al-Wajiz Wahidi", language: "ar" },
  { slug: "alrab-al-quran-li-da-as", name: "Alrab Al-Quran li-Da'as", authorName: "Alrab Al-Quran li-Da'as", language: "ar" },
  { slug: "ar-tafsir-al-mukhtasar", name: "Arabic Al-Mukhtasar in interpreting the Noble Quran", authorName: "Tafsir Center for Quranic Studies", language: "ar" },
  { slug: "asseraj-fi-bayan-gharib-alquran", name: "Asseraj fi Bayan Gharib AlQuran", authorName: "Asseraj fi Bayan Gharib AlQuran", language: "ar" },
  { slug: "ayah-dependency-graphs", name: "Ayah Dependency Graphs", authorName: "Ayah Dependency Graphs", language: "ar" },
  { slug: "fath-al-bayan-li-al-qanuji", name: "Fath Al-Bayan li Al-Qanuji", authorName: "Fath Al-Bayan li Al-Qanuji", language: "ar" },
  { slug: "fath-al-qadir-al-shawkani", name: "Fath Al-Qadir Al-Shawkani", authorName: "Fath Al-Qadir Al-Shawkani", language: "ar" },
  { slug: "i-rab-al-quran-li-al-darwish", name: "I'rab Al Quran li Al Darwish", authorName: "I'rab Al Quran li Al Darwish", language: "ar" },
  { slug: "al-i-rab-al-muyassar", name: "Iraab Al-Muyassar", authorName: "Iraab Al-Muyassar", language: "ar" },
  { slug: "jamia-al-bayan-aliji", name: "Jamia Al-Bayan AlIji", authorName: "Jamia Al-Bayan AlIji", language: "ar" },
  { slug: "mahasin-al-ta-wil-al-qasimi", name: "Mahasin Al-Ta'wil Al-Qasimi", authorName: "Mahasin Al-Ta'wil Al-Qasimi", language: "ar" },
  { slug: "mawsoo-at-al-tafsir-al-ma-thoor", name: "Mawsoo'at Al-Tafsir Al-Ma'thoor", authorName: "Mawsoo'at Al-Tafsir Al-Ma'thoor", language: "ar" },
  { slug: "nazam-al-durar-al-biqa-i", name: "Nazam Al-Durar Al-Biqa'i", authorName: "Nazam Al-Durar Al-Biqa'i", language: "ar" },
  { slug: "tadabbur-wa-amal", name: "Tadabbur wa 'Amal", authorName: "Tadabbur wa 'Amal", language: "ar" },
  { slug: "ar-tafseer-al-qurtubi", name: "Tafseer Al Qurtubi", authorName: "Qurtubi", language: "ar" },
  { slug: "ar-tafseer-al-saddi", name: "Tafseer Al Saadi - Arabic", authorName: "Saddi", language: "ar" },
  { slug: "ar-tafsir-al-baghawi", name: "Tafseer Al-Baghawi", authorName: "Baghawy", language: "ar" },
  { slug: "ar-tafseer-tanwir-al-miqbas", name: "Tafseer Tanwir al-Miqbas", authorName: "Tanweer", language: "ar" },
  { slug: "tafsir-abi-al-su-ood", name: "Tafsir Abi Al-Suaood", authorName: "Tafsir Abi Al-Suaood", language: "ar" },
  { slug: "ar-tafsir-al-wasit", name: "Tafsir Al Wasit", authorName: "Waseet", language: "ar" },
  { slug: "tafsir-al-alusi", name: "Tafsir Al-Alusi", authorName: "Tafsir Al-Alusi", language: "ar" },
  { slug: "tafsir-al-baydawi", name: "Tafsir Al-Baydawi", authorName: "Tafsir Al-Baydawi", language: "ar" },
  { slug: "tafsir-al-mawardi", name: "Tafsir Al-Mawardi", authorName: "Tafsir Al-Mawardi", language: "ar" },
  { slug: "tafsir-al-nasafi", name: "Tafsir Al-Nasafi", authorName: "Tafsir Al-Nasafi", language: "ar" },
  { slug: "tafsir-al-razi", name: "Tafsir Al-Razi", authorName: "Tafsir Al-Razi", language: "ar" },
  { slug: "tafsir-al-sam-ani", name: "Tafsir Al-Sam'ani", authorName: "Tafsir Al-Sam'ani", language: "ar" },
  { slug: "tafsir-al-samarqandi", name: "Tafsir Al-Samarqandi", authorName: "Tafsir Al-Samarqandi", language: "ar" },
  { slug: "ar-tafsir-al-tabari", name: "Tafsir al-Tabari", authorName: "Tabari", language: "ar" },
  { slug: "ar-tafseer-tahrir-al-tanwir", name: "Tafsir al-Tahrir wa al-Tanwir", authorName: "Tafsir al-Tahrir wa al-Tanwir", language: "ar" },
  { slug: "ar-tafsir-al-tha-alibi", name: "Tafsir Al-Tha'alibi", authorName: "Tafsir Al-Tha'alibi", language: "ar" },
  { slug: "ar-tafsir-as-saadi", name: "Tafsir As-Saadi", authorName: "Tafsir As-Saadi", language: "ar" },
  { slug: "tafsir-ibn-abi-hatim", name: "Tafsir Ibn Abi Hatim", authorName: "Tafsir Ibn Abi Hatim", language: "ar" },
  { slug: "tafsir-ibn-abi-zamanin", name: "Tafsir Ibn Abi Zamanin", authorName: "Tafsir Ibn Abi Zamanin", language: "ar" },
  { slug: "tafsir-ibn-al-jawzi", name: "Tafsir Ibn Al-Jawzi", authorName: "Tafsir Ibn Al-Jawzi", language: "ar" },
  { slug: "tafsir-ibn-al-qayyim", name: "Tafsir Ibn Al-Qayyim", authorName: "Tafsir Ibn Al-Qayyim", language: "ar" },
  { slug: "tafsir-ibn-juzay", name: "Tafsir Ibn Juzay", authorName: "Tafsir Ibn Juzay", language: "ar" },
  { slug: "ar-tafsir-ibn-kathir", name: "Tafsir Ibn Kathir", authorName: "Hafiz Ibn Kathir", language: "ar" },
  { slug: "tafsir-ibn-uthaymeen", name: "Tafsir Ibn Uthaymeen", authorName: "Tafsir Ibn Uthaymeen", language: "ar" },
  { slug: "ar-tafsir-al-jalalayn", name: "Tafsir Jalalayn", authorName: "Jalal al-Din al-Mahalli and Jalal al-Din al-Suyuti", language: "ar" },
  { slug: "tafsir-makhi", name: "Tafsir Makhi", authorName: "Tafsir Makhi", language: "ar" },
  { slug: "ar-tafsir-muyassar", name: "Tafsir Muyassar", authorName: "المیسر", language: "ar" },
  { slug: "tahlil-kalimat-al-qur-an", name: "Tahlil Kalimat al-Qur'an", authorName: "Tahlil Kalimat al-Qur'an", language: "ar" },
  { slug: "assamese-mokhtasar", name: "Assamese Abridged Explanation of the Quran", authorName: "Assamese Abridged Explanation of the Quran", language: "as" },
  { slug: "azeri-mokhtasar", name: "Azeri Mokhtasar", authorName: "Azeri Mokhtasar", language: "az" },
  { slug: "bengali-mokhtasar", name: "Bengali Abridged Explanation of the Quran", authorName: "Bengali Abridged Explanation of the Quran", language: "bn" },
  { slug: "bn-tafseer-ibn-e-kaseer", name: "Tafseer ibn Kathir", authorName: "Tawheed Publication", language: "bn" },
  { slug: "bn-tafsir-abu-bakr-zakaria", name: "Tafsir Abu Bakr Zakaria", authorName: "King Fahd Quran Printing Complex", language: "bn" },
  { slug: "bn-tafsir-ahsanul-bayaan", name: "Tafsir Ahsanul Bayaan", authorName: "Bayaan Foundation", language: "bn" },
  { slug: "bn-tafisr-fathul-majid", name: "Tafsir Fathul Majid", authorName: "AbdulRahman Bin Hasan Al-Alshaikh", language: "bn" },
  { slug: "bosnian-mokhtasar", name: "Bosnian Abridged Explanation of the Quran", authorName: "Bosnian Abridged Explanation of the Quran", language: "bs" },
  { slug: "en-al-qushairi-tafsir", name: "Al Qushairi Tafsir", authorName: "Al Qushairi Tafsir", language: "en" },
  { slug: "en-al-jalalayn", name: "Al-Jalalayn", authorName: "Al-Jalalayn", language: "en" },
  { slug: "en-asbab-al-nuzul-by-al-wahidi", name: "Asbab Al-Nuzul by Al-Wahidi", authorName: "Asbab Al-Nuzul by Al-Wahidi", language: "en" },
  { slug: "en-tafsir-al-mukhtasar", name: "English Al-Mukhtasar", authorName: "Tafsir Center for Quranic Studies", language: "en" },
  { slug: "en-kashani-tafsir", name: "Kashani Tafsir", authorName: "Kashani Tafsir", language: "en" },
  { slug: "en-kashf-al-asrar-tafsir", name: "Kashf Al-Asrar Tafsir", authorName: "Kashf Al-Asrar Tafsir", language: "en" },
  { slug: "en-tafsir-maarif-ul-quran", name: "Maarif-ul-Quran", authorName: "Mufti Muhammad Shafi", language: "en" },
  { slug: "tafsir-al-jalalayn", name: "Tafsir Al Jalalayn - English", authorName: "Tafsir Al Jalalayn - English", language: "en" },
  { slug: "en-tafsir-al-tustari", name: "Tafsir al-Tustari", authorName: "Tafsir al-Tustari", language: "en" },
  { slug: "en-tafisr-ibn-kathir", name: "Tafsir Ibn Kathir", authorName: "Hafiz Ibn Kathir", language: "en" },
  { slug: "en-tafsir-ibn-abbas", name: "Tanwîr al-Miqbâs min Tafsîr Ibn ‘Abbâs", authorName: "Tanwîr al-Miqbâs min Tafsîr Ibn ‘Abbâs", language: "en" },
  { slug: "en-tazkirul-quran", name: "Tazkirul Quran(Maulana Wahiduddin Khan)", authorName: "Maulana Wahid Uddin Khan", language: "en" },
  { slug: "spanish-mokhtasar", name: "Spanish Abridged Explanation of the Quran", authorName: "Spanish Abridged Explanation of the Quran", language: "es" },
  { slug: "persian-mokhtasar", name: "Persian Al-Mukhtasar in interpreting the Noble Quran", authorName: "Persian Al-Mukhtasar in interpreting the Noble Quran", language: "fa" },
  { slug: "fr-tafsir-as-saadi", name: "Tafsir As-Saadi - Persian", authorName: "Tafsir As-Saadi - Persian", language: "fa" },
  { slug: "fulani-mokhtasar", name: "Fulani Mokhtasar", authorName: "Fulani Mokhtasar", language: "ff" },
  { slug: "french-mokhtasar", name: "French Abridged Explanation of the Quran", authorName: "French Abridged Explanation of the Quran", language: "fr" },
  { slug: "hindi-mokhtasar", name: "Hindi Mokhtasar", authorName: "Hindi Mokhtasar", language: "hi" },
  { slug: "indonesian-mokhtasar", name: "Indoniesua Al-Mukhtasar in Interpreting the Noble Quran", authorName: "Indoniesua Al-Mukhtasar in Interpreting the Noble Quran", language: "id" },
  { slug: "id-tafsir-as-saadi", name: "Tafsir As-Saadi - Indonesian", authorName: "Tafsir As-Saadi - Indonesian", language: "id" },
  { slug: "in-tafsir-jalalayn", name: "Tafsir Jalalayn", authorName: "Tafsir Jalalayn", language: "id" },
  { slug: "italian-mokhtasar", name: "Italian Al-Mukhtasar in interpreting the Noble Quran", authorName: "Italian Al-Mukhtasar in interpreting the Noble Quran", language: "it" },
  { slug: "japanese-mokhtasar", name: "Japanese Abridged Explanation of the Quran", authorName: "Japanese Abridged Explanation of the Quran", language: "ja" },
  { slug: "khmer-mokhtasar", name: "Khmer Abridged Explanation of the Quran", authorName: "Khmer Abridged Explanation of the Quran", language: "km" },
  { slug: "kurdish-mokhtasar", name: "Kurdish Mokhtasar", authorName: "Kurdish Mokhtasar", language: "ku" },
  { slug: "kurd-tafsir-rebar", name: "Rebar Kurdish Tafsir", authorName: "Rebar Kurdish Tafsir", language: "ku" },
  { slug: "kyrgyz-mokhtasar", name: "Kyrgyz Mokhtasar", authorName: "Kyrgyz Mokhtasar", language: "ky" },
  { slug: "malayalam-mokhtasar", name: "Malayalam Abridged Explanation of the Quran", authorName: "Malayalam Abridged Explanation of the Quran", language: "ml" },
  { slug: "pashto-mokhtasar", name: "Pashto Mokhtasar", authorName: "Pashto Mokhtasar", language: "ps" },
  { slug: "russian-mokhtasar", name: "Russian Al-Mukhtasar", authorName: "Russian Al-Mukhtasar", language: "ru" },
  { slug: "ru-tafseer-al-saddi", name: "Tafseer Al Saadi - Russian", authorName: "Saddi", language: "ru" },
  { slug: "tafsir-as-saadi-russian", name: "Tafsir As-Saadi", authorName: "Tafsir As-Saadi", language: "ru" },
  { slug: "ru-tafsir-ibne-kahtir", name: "Tafsir Ibne Kathir", authorName: "Tafsir Ibne Kathir", language: "ru" },
  { slug: "sinhalese-mokhtasar", name: "Sinhalese Mokhtasar", authorName: "Sinhalese Mokhtasar", language: "si" },
  { slug: "sq-saadi", name: "Tafsir As-Saadi", authorName: "Tafsir As-Saadi", language: "sq" },
  { slug: "serbian-mokhtasar", name: "Serbian Mokhtasar", authorName: "Serbian Mokhtasar", language: "sr" },
  { slug: "tamil-mokhtasar", name: "Tamil Mokhtasar", authorName: "Tamil Mokhtasar", language: "ta" },
  { slug: "telugu-mokhtasar", name: "Telugu Mokhtasar", authorName: "Telugu Mokhtasar", language: "te" },
  { slug: "thai-mokhtasar", name: "Thai Mokhtasar", authorName: "Thai Mokhtasar", language: "th" },
  { slug: "tagalog-mokhtasar", name: "Filipino (Tagalog) Al-Mukhtasar in interpreting the Noble Quran", authorName: "Filipino (Tagalog) Al-Mukhtasar in interpreting the Noble Quran", language: "tl" },
  { slug: "turkish-tafsir-as-saadi-turkish", name: "Tafsir As-Saadi - Turkish", authorName: "Tafsir As-Saadi - Turkish", language: "tr" },
  { slug: "tr-tafsir-ibne-kathir", name: "Tafsir Ibne Kathir", authorName: "Tafsir Ibne Kathir", language: "tr" },
  { slug: "turkish-mokhtasar", name: "Turkish Al-Mukhtasar in Interpreting the Noble Quran", authorName: "Turkish Al-Mukhtasar in Interpreting the Noble Quran", language: "tr" },
  { slug: "uyghur-mokhtasar", name: "Uyghur Mokhtasar", authorName: "Uyghur Mokhtasar", language: "ug" },
  { slug: "ur-tafsir-fe-zalul-quran-syed-qatab", name: "Fi Zilal al-Quran", authorName: "Sayyid Ibrahim Qutb", language: "ur" },
  { slug: "ur-tafsir-as-saadi-urdu", name: "Tafsir As-Saadi - Urdu", authorName: "Tafsir As-Saadi - Urdu", language: "ur" },
  { slug: "ur-tafsir-bayan-ul-quran", name: "Tafsir Bayan ul Quran", authorName: "Dr. Israr Ahmad", language: "ur" },
  { slug: "ur-tafseer-ibn-e-kaseer", name: "Tafsir Ibn Kathir", authorName: "Hafiz Ibn Kathir", language: "ur" },
  { slug: "ur-tazkirul-quran", name: "Tazkirul Quran(Maulana Wahiduddin Khan)", authorName: "Maulana Wahid Uddin Khan", language: "ur" },
  { slug: "uzbek-mokhtasar", name: "Uzbek Mokhtasar", authorName: "Uzbek Mokhtasar", language: "uz" },
  { slug: "vietnamese-mokhtasar", name: "Vietnamese Al-Mukhtasar in interpreting the Noble Quran", authorName: "Vietnamese Al-Mukhtasar in interpreting the Noble Quran", language: "vi" },
  { slug: "chinese-mokhtasar", name: "Chinese Abridged Explanation of the Quran", authorName: "Chinese Abridged Explanation of the Quran", language: "zh" },
];
